language: cpp
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-6 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 60 
  - sudo apt-get install -y -qq libboost-test-dev doxygen graphviz
script:
  - cmake -H. -BBuild
  - cmake --build Build
  - cmake --build Build --target test
  - cmake --build Build --target package
  - doxygen doxygen.cfg
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T Build/print_ip_pkg-*.$TRAVIS_BUILD_NUMBER-Linux.deb -utatyana-otus:$BINTRAY_API_KEY "https://api.bintray.com/content/tatyana-otus/hw_otus/print_ip/$TRAVIS_BUILD_NUMBER/print_ip_pkg-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: pages
    skip-cleanup: true
    local_dir: html/
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    on:
     branch: master