before_script:
  - sudo apt-get install doxygen
script:
  - doxygen ../doxygen.cfg
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: html/
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true