language: cpp
compiler: clang
before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo apt-get install doxygen
script:
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
  - doxygen ../doxygen.cfg
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - curl -T print_ip_pkg-*.$TRAVIS_BUILD_NUMBER-Linux.deb -utatyana-otus:$BINTRAY_API_KEY "https://api.bintray.com/content/tatyana-otus/hw_otus/print_ip/$TRAVIS_BUILD_NUMBER/print_ip_pkg-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: pages
    skip-cleanup: true
    local_dir: build/html/
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
     branch: master